name: fileats
description: "FILeats - No Worry, No Antri, Just Feel It"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gabarito
      fonts:
        - asset: fonts/Gabarito-VariableFont_wght.ttf

  assets:
    - assets/images/assets/fileat_logo.png
    - assets/images/assets/Google_logo.png
    - assets/images/assets/back_button.png
    - assets/images/assets/role.png
    - assets/images/assets/FILeats.png
    - assets/images/assets/communities.png
    - assets/images/assets/rightArrow.png
    - assets/images/homepage_menumakan/fileat_kue.png
    - assets/images/homepage_menumakan/fileat_mie.png
    - assets/images/homepage_menumakan/fileat_minuman.png
    - assets/images/homepage_menumakan/fileat_nasi.png
    - assets/images/homepage_menumakan/fileat_snack.png
    - assets/images/navbar/Community.png
    - assets/images/navbar/s_Community.png
    - assets/images/navbar/Home.png
    - assets/images/navbar/s_Home.png
    - assets/images/navbar/orders.png
    - assets/images/navbar/s_orders.png
    - assets/images/navbar/Profile.png
    - assets/images/navbar/s_Profile.png
    - assets/images/menumakan_toko/n_a_Bakar.jpg
    - assets/images/menumakan_toko/n_a_Crispy.jpg
    - assets/images/menumakan_toko/n_a_ungkep.jpg
    - assets/images/menumakan_toko/n_gila.jpg
    - assets/images/menumakan_toko/n_goreng.jpg
    - assets/images/menumakan_toko/n_KulitAyam.jpg
    - assets/images/menumakan_toko/n_kuning.jpg
    - assets/images/menumakan_toko/n_padang.jpg
    - assets/images/menumakan_toko/n_usus.jpg
    - assets/images/menumakan_toko/indomie_g.jpg
    - assets/images/menumakan_toko/indomie_k.jpg
    - assets/images/menumakan_toko/mie_ayam.jpg
    - assets/images/assets/avatarToko/wrung_bangdor.jpg
    - assets/images/assets/avatarToko/wrung_bindah.jpg
    - assets/images/assets/avatarToko/wrung_m_elly.jpg
    - assets/images/assets/avatarToko/comingsoon.jpg
