name: fileats
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  faker: ^2.2.0
  flutter_color:
  flutter_native_splash: ^2.4.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "images/assets/splashScreen1.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  fonts:
    - family: Gabarito
      fonts:
        - asset: fonts/Gabarito-VariableFont_wght.ttf

  assets:
    - assets/images/assets/fileat_logo.png
    - assets/images/assets/Google_logo.png
    - assets/images/assets/back_button.png
    - assets/images/assets/role.png
    - assets/images/assets/FILeats.png
    - assets/images/assets/communities.png
    - assets/images/assets/rightArrow.png
    - assets/images/homepage_menumakan/fileat_kue.png
    - assets/images/homepage_menumakan/fileat_mie.png
    - assets/images/homepage_menumakan/fileat_minuman.png
    - assets/images/homepage_menumakan/fileat_nasi.png
    - assets/images/homepage_menumakan/fileat_snack.png
    - assets/images/navbar/Community.png
    - assets/images/navbar/s_Community.png
    - assets/images/navbar/Home.png
    - assets/images/navbar/s_Home.png
    - assets/images/navbar/orders.png
    - assets/images/navbar/s_orders.png
    - assets/images/navbar/Profile.png
    - assets/images/navbar/s_Profile.png
    - assets/images/menumakan_toko/n_a_Bakar.jpg
    - assets/images/menumakan_toko/n_a_Crispy.jpg
    - assets/images/menumakan_toko/n_a_ungkep.jpg
    - assets/images/menumakan_toko/n_gila.jpg
    - assets/images/menumakan_toko/n_goreng.jpg
    - assets/images/menumakan_toko/n_KulitAyam.jpg
    - assets/images/menumakan_toko/n_kuning.jpg
    - assets/images/menumakan_toko/n_padang.jpg
    - assets/images/menumakan_toko/n_usus.jpg
    - assets/images/menumakan_toko/indomie_g.jpg
    - assets/images/menumakan_toko/indomie_k.jpg
    - assets/images/menumakan_toko/mie_ayam.jpg
    - assets/images/assets/avatarToko/wrung_bangdor.jpg
    - assets/images/assets/avatarToko/wrung_bindah.jpg
    - assets/images/assets/avatarToko/wrung_m_elly.jpg
    - assets/images/assets/avatarToko/comingsoon.jpg
